FROM rasa/rasa:3.6.20-full

# The Rasa SDK image runs as non-root user by default. Hence, you have to switch
# back to the `root` user if you want to install additional dependencies

USER root

RUN pip3 install beautifulsoup4==4.9.3
RUN pip3 install python-decouple==3.3
RUN pip3 install fuzzywuzzy
# Switch back to a non-root user
USER 1001