services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: master123
      POSTGRES_MULTIPLE_DATABASES: zammad,intent,ussd,ussd-custom,deepspeech # comma,separated,list,of,databases
    volumes:
      - maindb_data:/var/lib/postgresql/data
      - ../postgres:/docker-entrypoint-initdb.d
    networks:
      - infrastructure_default
    ports:
      - 5632:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    profiles:
      - ussd
      - ivr
      - chat
      - voicechat

  adminer:
    image: dpage/pgadmin4:latest
    entrypoint: >
      /bin/sh -c "
      /entrypoint.sh
      " 
    user: "root:root"
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "88:80"
    networks:
      - infrastructure_default
    volumes:
      - ../pgadmin/servers.json:/pgadmin4/servers.json
      - ../pgadmin/pgpass:/var/lib/pgadmin/.pgpass
    profiles:
      - ussd
      - ivr
      - chat
      - voicechat

volumes:
  maindb_data:
    driver: local

networks:
  infrastructure_default:
    external: true
