services:

  tts:
    container_name: mbaza-tts
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
      labels:
        - mbaza-tts
    ports:
      - "6901:6901"
    environment:
      - THREADS=2
      - PROCESSES=1 # allow 2250 MB /x1 worker
      - TIMEOUT=480 # worker timeout
      - GRACEFUL_TIMEOUT=450 # worker timeout
      - SRV_HOST=0.0.0.0
      - SRV_PORT=6901
      - APP_LANG=eng
      - APP_SENTENCE_MAX_WORDS=40
      - APP_SENTENCE_INFER_BATCH_SIZE=10 # allow around 550MB /x1 APP_SENTENCE_INFER_BATCH_SIZE
      - APP_SAMPLE_TEXT=. This is a sample input text .
      - APP_LOG_LEVEL=debug
    networks:
      - infrastructure_default
    profiles:
      - ivr

networks:
  infrastructure_default:
    external: true

#  mbaza-tts-caddy:
#    image: caddy:2-alpine
#    container_name: mbaza-tts-caddy
#    restart: unless-stopped
#    env_file:
#      - .env
#    ports:
#      - "5001:5001"
#    environment:
#      - PROXY_TARGET=mbaza-tts-eng-cpu:6901
#    volumes:
#      - $PWD/Caddyfile:/etc/caddy/Caddyfile
#      - caddy_data:/data
#      - caddy_config:/config
#    depends_on:
#      - mbaza-tts-eng-cpu
#
#volumes:
#  caddy_data:
#    external: true
#  caddy_config:
