services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      RABBITMQ_DEFAULT_PASS: ${PASSWORD}
      RABBITMQ_DEFAULT_USER: ${USERNAME}
      RABBITMQ_DEFAULT_VHOST: ${DEFAULT_HOST}
    networks:
      - infrastructure_default
    profiles:
      - ussd
      - ivr
      - chat
      - voicechat


networks:
  infrastructure_default: # external network
    external: true